### ISSUE TITLE
Development status?

### ISSUE THREAD

**Issue by JoeDuncko** [AgeOfMobile/Calendar-Mac#1]
Hi! I'm looking for an open source solution that mimics Windows' functionality of being able to click the time at the top right of the Mac toolbar and get a mini calendar that highlights the current day. It looks like your tool does the job (according to the screenshot) but it doesn't look like you have any releases. Do you plan on doing so, or is this project abandoned?

**Comment by AgeOfMobile** [comment]
Hi, this is just a sample project which demonstrate how to develop a calendar widget in Swift, not a real product. If you're interested in, I will make a release so you can install on your Mac or check out code and build it yourself.

**Comment by JoeDuncko** [comment]
Sorry for the delay! I'd be interested in a release so I could check out your work, then I'd consider making changes myself. I'm very new to Mac app dev. Thanks!

**Comment by AgeOfMobile** [comment]
@JoeDuncko You can download the app here: https://dl.dropboxusercontent.com/u/5679707/SimpleCalendar.app.zip

**Comment by JoeDuncko** [comment]
Awesome, thanks! I'll take a look at it and then consider contributing!
